# Cloud Build Configuration for Delivery Tracking API

## `cloudbuild.yaml`

```yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/delivery-tracking-api:${_IMAGE_TAG}'
      - '.'
    dir: 'legacy-java-app' # Assuming the app is in this directory relative to the Cloud Build context

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/delivery-tracking-api:${_IMAGE_TAG}'

  # Step 3: Deploy to GKE
  # Ensure gcloud is authenticated to the GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Get GKE Credentials
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'delivery-tracking-gke-cluster' # Name of your GKE cluster (from Terraform)
      - '--region=${_GCP_REGION}'
      - '--project=${PROJECT_ID}'

  # Step 4: Apply Kubernetes Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Apply Deployment
    args:
      - 'apply'
      - '-f'
      - 'delivery-tracking-api-deployment.yaml' # This file would be generated by Terraform or manually created
      - '-n'
      - 'default' # Or your dedicated namespace
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GCP_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=delivery-tracking-gke-cluster'

  # Step 5: Apply Kubernetes Service
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Apply Service
    args:
      - 'apply'
      - '-f'
      - 'delivery-tracking-api-service.yaml' # This file would be generated by Terraform or manually created
      - '-n'
      - 'default' # Or your dedicated namespace
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GCP_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=delivery-tracking-gke-cluster'

# Substitutions for dynamic values
substitutions:
  _IMAGE_TAG: 'latest' # Default image tag, can be overridden
  _GCP_REGION: 'us-central1' # Default GCP region, can be overridden

images:
  - 'gcr.io/${PROJECT_ID}/delivery-tracking-api:${_IMAGE_TAG}'
```
